codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project: on
      target: 50%
      #threshold: 0%
    patch: off
      target: auto
      #threshold: 0%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no